name: Deploy CDK Stack

on:
  push:
    branches:
      - main
    paths:
      - "plan_obs/**"  # Runs only if files in the "plan_obs" folder change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: |
          cd cdk
          npm install

      - name: Synthesize CDK
        run: |
          cd cdk
          cdk synth

      - name: Deploy CDK Stack
        run: |
          cd cdk
          cdk deploy --require-approval never
